### ISSUE TITLE
binary-ui-components build for React and React Native

### ISSUE THREAD

**Issue by josh0707** [opensource-cards/binary-ui#12]
Hi @rtkhanas , 
Thanks for your module.

I would like to use the binary-ui-components part of your repository in my project.
However, binary-ui-components/package.json does not offer the option to either build for React web or build for React native.

How do you manage to include only the files required for React web or React native in your build or to get your module to load the web or native files depending on the platform? 

i.e. including /components-styled/ActionButtonStyled/index.js instead of /components-styled/ActionButtonStyled/index.native.js

Thanks,

Josh

**Comment by rtkhanas** [comment]
Hi Josh,

Thank you for your interest in this repo.

Due to React Native [documentation](https://facebook.github.io/react-native/docs/platform-specific-code.html), it automatically recognizes files with .ios and .android prefixes. Once you have 3 files: `index.js`, `index.ios.js` and `index.android.js` the `index.js` files will be used for web and other 2 will be included in React Native build.

However, I also noticed that just `.native.js` postfix is enough to be included in the build for React Native. I haven't found that in any official doc though.

Ross

**Comment by josh0707** [comment]
Thank you, I didn't know about `.native.js`. I am still looking at your package. I might have more questions but, if you don't mind, will likely ask them via email if not related to any issue.

Josh

**Comment by rtkhanas** [comment]
Sure, feel free to ask. We will pay for attention to this package soon btw, especially to RN version.
